spring.application.name=clinicapp
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/ClinicApp
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
stripe.api.key=sk_test_
stripe.webhook.secret=whsec_c3
app.frontend.url=http://localhost:8081
logging.level.root=info

logging.file.name=logs/app.log
jwt.secret=MySuperSecretKeyForJWTAuthSystemSpringSecurity2026ProjectAppHalaa!